[package]
authors = ["The Rust Project Developers"]
name = "serialize"
version = "0.0.0"

[lib]
name = "serialize"
path = "lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies.smallvec]
git = "https://github.com/Zoxc/rust-smallvec"
branch = "push_light_def"
features = ["union", "likely", "push_light"]
