[package]
authors = ["The Rust Project Developers"]
name = "rustc_apfloat"
version = "0.0.0"

[lib]
name = "rustc_apfloat"
path = "lib.rs"

[dependencies]
bitflags = "1.0"
rustc_cratesio_shim = { path = "../librustc_cratesio_shim" }

[dependencies.smallvec]
git = "https://github.com/Zoxc/rust-smallvec"
branch = "push_light_def"
features = ["union", "likely", "push_light"]
