use std::borrow::Cow;
use std::marker::PhantomData;

use rustc_data_structures::inspect::{self, EnumVariant, Value};
use rustc_data_structures::stable_hasher::{HashStable, SpanArgs, StructureState};
use rustc_hir::def_id::CrateNum;
use rustc_middle::ty::TyCtxt;
use rustc_query_system::ich::StableHashingContext;
use rustc_span::{CachingSourceMapView, Pos, Span};

// NOTE: `PER_QUERY_COLLECT_STRUCTURES_FNS` is generated by the query
// macro into the plumbing module; do not import it here.
use crate::PER_QUERY_COLLECT_STRUCTURES_FNS;
use std::fs;
use std::io::{ Write, Seek, SeekFrom};
use std::path::PathBuf;
use rustc_span::def_id::LOCAL_CRATE;
use snap::write::FrameEncoder;
// Cursor was used in an earlier approach; no longer needed.

fn def_path_value<'tcx>(tcx: TyCtxt<'tcx>, crate_num: u32, index: u32,
    state: &mut StructureState<'_, StableHashingContext<'_>>,) -> inspect::Value {
    // Construct a `DefId` from the supplied `u32` crate/def indices
    // and return an `inspect::Value::String` containing the def path.
    let def_id = rustc_span::def_id::DefId {
        krate: rustc_span::def_id::CrateNum::from_u32(crate_num),
        index: rustc_span::def_id::DefIndex::from_u32(index),
    };
    tcx.def_path(def_id).structure(state)
}

fn crate_num_value<'tcx>(tcx: TyCtxt<'tcx>, crate_num: u32,
    state: &mut StructureState<'_, StableHashingContext<'_>>,) -> inspect::Value {
        tcx.def_path_hash(
        CrateNum::from_u32(crate_num).as_def_id()).stable_crate_id().structure(state)
}

fn span_value(
    tcx: TyCtxt<'_>,
    span_args: SpanArgs,
    state: &mut StructureState<'_, StableHashingContext<'_>>,
) -> inspect::Value {
    let span = Span::from_args(span_args);

    let span = span.data_untracked();
    let ctx_val = span.ctxt.structure(state);
    let parent_val = span.parent.structure(state);

    if span.is_dummy() {
        return Value::Enum {
            path: std::borrow::Cow::Borrowed("Span"),
            variant: EnumVariant::Unit(std::borrow::Cow::Borrowed("Dummy")),
        };
    }

    let parent = span.parent.map(|parent| tcx.def_span(parent).data_untracked());
    if let Some(parent) = parent
        && parent.contains(span)
    {
        // This span is enclosed in a definition: only hash the relative position. This catches
        // a subset of the cases from the `file.contains(parent.lo)`. But we can do this check
        // cheaply without the expensive `span_data_to_lines_and_cols` query.
        let lo = (span.lo - parent.lo).to_u32();
        let hi = (span.hi - parent.lo).to_u32();
        return Value::Enum {
            path: Cow::Borrowed("Span"),
            variant: EnumVariant::Named(
                Cow::Borrowed("Relative"),
                vec![
                    (Cow::Borrowed("ctxt"), ctx_val),
                    (Cow::Borrowed("parent"), parent_val),
                    (Cow::Borrowed("lo"), lo.structure(state)),
                    (Cow::Borrowed("hi"), hi.structure(state)),
                ],
            ),
        };
    }

    let mut caching = CachingSourceMapView::new(tcx.sess.source_map());

    // If this is not an empty or invalid span, we want to hash the last position that belongs
    // to it, as opposed to hashing the first position past it.
    let Some((file, line_lo, col_lo, line_hi, col_hi)) = caching.span_data_to_lines_and_cols(&span)
    else {
        return Value::Enum {
            path: std::borrow::Cow::Borrowed("Span"),
            variant: EnumVariant::Unit(std::borrow::Cow::Borrowed("Dummy")),
        };
    };

    if let Some(parent) = parent
        && file.contains(parent.lo)
    {
        // This span is relative to another span in the same file,
        // only hash the relative position.
        let lo = span.lo.0.wrapping_sub(parent.lo.0);
        let hi = span.hi.0.wrapping_sub(parent.lo.0);
        return Value::Enum {
            path: Cow::Borrowed("Span"),
            variant: EnumVariant::Named(
                Cow::Borrowed("Relative"),
                vec![
                    (Cow::Borrowed("ctxt"), ctx_val),
                    (Cow::Borrowed("parent"), parent_val),
                    (Cow::Borrowed("lo"), lo.structure(state)),
                    (Cow::Borrowed("hi"), hi.structure(state)),
                ],
            ),
        };
    }

    // Hash both the length and the end location (line/column) of a span. If we hash only the
    // length, for example, then two otherwise equal spans with different end locations will
    // have the same hash. This can cause a problem during incremental compilation wherein a
    // previous result for a query that depends on the end location of a span will be
    // incorrectly reused when the end location of the span it depends on has changed (see
    // issue #74890). A similar analysis applies if some query depends specifically on the
    // length of the span, but we only hash the end location. So hash both.
    let len = (span.hi - span.lo).0;

    Value::Enum {
        path: Cow::Borrowed("Span"),
        variant: EnumVariant::Named(
            Cow::Borrowed("Valid"),
            vec![
                (Cow::Borrowed("ctxt"), ctx_val),
                (Cow::Borrowed("parent"), parent_val),
                (Cow::Borrowed("stable_id"), file.stable_id.structure(state)),
                (Cow::Borrowed("col_lo"), col_lo.structure(state)),
                (Cow::Borrowed("col_hi"), col_hi.structure(state)),
                (Cow::Borrowed("line_lo"), line_lo.structure(state)),
                (Cow::Borrowed("line_hi"), line_hi.structure(state)),
                (Cow::Borrowed("len"), len.structure(state)),
            ],
        ),
    }
}

/// Collects structural representations for all queries and returns
/// them as an inspect::Value map: query_name -> { key -> value }
pub(crate) fn collect_all_query_structures<'tcx>(
    tcx: TyCtxt<'tcx>,
    // Optional file to which per-query compressed payloads will be written as
    // we iterate over PER_QUERY_COLLECT_STRUCTURES_FNS. We need Seek to
    // obtain current offsets. If `None` is passed, we will not write payloads
    // but instead hash each per-query `Map` value and store that hash.
    file: Option<&mut fs::File>,
) -> Result<inspect::Value, ()> {
    let mut state = StructureState::<'_, StableHashingContext<'_>> {
        schema_list: Default::default(),
        file,
        def_path: &|crate_num, index, state| def_path_value(tcx, crate_num, index, state),
        crate_num: &|crate_num, state| crate_num_value(tcx, crate_num, state),
        span_value: &|args, state| span_value(tcx, args, state),
        _marker: PhantomData,
    };

    let mut out: Vec<(inspect::Value, inspect::Value)> = Vec::new();

    // hashing/compression is handled per-query in `assemble_query_structures`

    for f in PER_QUERY_COLLECT_STRUCTURES_FNS.iter() {
        let (name, value) = f(tcx, &mut state);
        out.push((inspect::Value::String(name.into()), value));
    }

    // Convert Vec into BTreeMap for the Map variant
    let mut entries_map: ::std::collections::BTreeMap<inspect::Value, inspect::Value> =
        ::std::collections::BTreeMap::new();
    for (k, v) in out.into_iter() {
        entries_map.insert(k, v);
    }

    Ok(inspect::Value::Map(entries_map))
}

// Module-scoped helper for exporting query structures when the feature is enabled.
pub(crate) fn export_queries_if_enabled<'tcx>(tcx: TyCtxt<'tcx>) {
    // Check option enablement on the unstable options struct.
    if !tcx.sess.opts.unstable_opts.export_queries {
        return;
    }

    let dir = match &tcx.sess.opts.unstable_opts.export_queries_dir {
        Some(d) => d.clone(),
        None => return,
    };

    let _prof_timer = tcx.sess.prof.verbose_generic_activity("export_queries");

    // Determine crate name and stable crate id early so the directory
    // scanning can use them. Use the stable crate id (not the crate
    // hash) in the filename to make the exported filename stable across
    // builds where only the crate hash may differ.
    let crate_name = tcx.crate_name(LOCAL_CRATE).to_string();
    let crate_stable_id = tcx.stable_crate_id(LOCAL_CRATE).as_u64();
    let crate_id_str = format!("{:08x}", crate_stable_id);

    // Ensure directory exists; if creation fails, emit a warning diagnostic.
    if let Err(e) = fs::create_dir_all(&dir) {
        tcx.sess.dcx().emit_warn(crate::error::ExportQueriesCreateDirFail {
            path: dir.as_path(),
            err: e.to_string(),
        });
        return;
    }

    // Compute a stable hash of the top-level structures (no file) and use
    // that as the unique filename. If the file already exists, return
    // without error.
    let top_no_file = {
        let _prof_timer = tcx.sess.prof.verbose_generic_activity("export_queries_hash_pass");

        match collect_all_query_structures(tcx, None) {
        Ok(v) => v,
        Err(_) => return,
    }};

    use std::hash::Hash;
    use rustc_hashes::Hash128;
    use rustc_data_structures::stable_hasher::StableHasher;

    let mut hasher = StableHasher::new();
    top_no_file.hash(&mut hasher);
    let h = hasher.finish::<Hash128>();
    let hex = format!("{:032x}", h.as_u128());

    let filename = format!("{}.{}.content-{}.rcqe", crate_name, crate_id_str, hex);
    let mut path = PathBuf::from(&dir);
    path.push(&filename);

    if path.exists() {
        // File with identical exported content already exists; nothing to do.
        return;
    }

    // Create the file to stream payloads into.
    let mut f = match fs::File::create(&path) {
        Ok(file) => file,
        Err(e) => {
            tcx.sess.dcx().emit_warn(crate::error::ExportQueriesFileWriteFail {
                path: path.as_path(),
                err: e.to_string(),
            });
            return;
        }
    };

    // Write a fixed, constant 8-byte u64 header so tools can recognize
    // this file format. The value is chosen to look random but remains
    // constant across runs.
    const MAGIC_HEADER_U64: u64 = 0x9e3793b97f4a7c15u64;
    let header_bytes = MAGIC_HEADER_U64.to_le_bytes();
    if f.write_all(&header_bytes).is_err() {
        tcx.sess.dcx().emit_warn(crate::error::ExportQueriesFileWriteFail {
            path: path.as_path(),
            err: "failed to write header".to_string(),
        });
        return;
    }

    // Collect and stream per-query payloads into `f`. This will write the
    // compressed per-query payloads and return a top-level `Value` where
    // those entries have been replaced with their offsets.
    let value = match collect_all_query_structures(tcx, Some(&mut f)) {
        Ok(v) => v,
        Err(_) => return,
    };

    // Now write the serialized top-level Value and footer length.
    let bytes = match bincode::serialize(&value) {
        Ok(b) => b,
        Err(_) => return,
    };

    if f.write_all(&bytes).is_err() {
        tcx.sess.dcx().emit_warn(crate::error::ExportQueriesFileWriteFail {
            path: path.as_path(),
            err: "failed to write top-level value".to_string(),
        });
        return;
    }
    // Store only the length of the serialized top-level value (u64 LE).
    // Readers can use this length to locate and validate the footer.
    let footer_len = bytes.len() as u64;
    if f.write_all(&footer_len.to_le_bytes()).is_err() {
        tcx.sess.dcx().emit_warn(crate::error::ExportQueriesFileWriteFail {
            path: path.as_path(),
            err: "failed to write footer length".to_string(),
        });
        return;
    }

    // Write a trailer magic so readers can quickly sanity-check that the
    // file ended as expected, then flush the OS buffers. Emit a warning
    // if either write or flush fails.
    let trailer_bytes = MAGIC_HEADER_U64.to_le_bytes();
    if f.write_all(&trailer_bytes).is_err() {
        tcx.sess.dcx().emit_warn(crate::error::ExportQueriesFileWriteFail {
            path: path.as_path(),
            err: "failed to write trailer magic".to_string(),
        });
        return;
    }

    // Ensure all writes succeeded by flushing the OS buffers. If flush
    // fails, emit a diagnostic so callers know the export may be incomplete.
    if f.flush().is_err() {
        tcx.sess.dcx().emit_warn(crate::error::ExportQueriesFileWriteFail {
            path: path.as_path(),
            err: "failed to flush output file".to_string(),
        });
        return;
    }

    // The remainder of the function finishes above (file creation, streaming,
    // writing top-level value and footer). No further actions needed here.
}

/// Assemble the final per-query structure map from the entries and metadata.
pub(crate) fn assemble_query_structures<'tcx, K, QV, C, F>(
    _tcx: TyCtxt<'tcx>,
    name: String,
    cache: &C,
    state: &mut StructureState<'_, StableHashingContext<'_>>,
    mut get_value: F,
) -> (String, inspect::Value)
where
    C: rustc_query_system::query::QueryCache<Key = K>,
    K: Clone,
    for<'s> K: HashStable<StableHashingContext<'s>>,
    QV: Sized,
    C::Value: Copy,
    F: FnMut(&K, &C::Value, &mut StructureState<'_, StableHashingContext<'_>>) -> inspect::Value,
{
    // Build entries by iterating the cache and using the provided closure
    // to obtain the value representation for each entry. The closure is
    // responsible for honoring `no_hash` semantics when necessary.
    let mut entries_map: ::std::collections::BTreeMap<inspect::Value, inspect::Value> =
        ::std::collections::BTreeMap::new();

    // Also capture the raw cached entries so consumers can access original
    // keys/values without calling `structure`. We clone the keys rather
    // than moving them out of the cache.
    let mut cached: Vec<(K, C::Value)> = Vec::new();
    cache.iter(&mut |k, v, _| {
        cached.push((k.clone(), *v));
    });

    for (k, v) in cached.iter() {
        let k_val = k.structure(state);
        let v_val = get_value(k, v, state);
        entries_map.insert(k_val, v_val);
    }

    let key_type_name = std::any::type_name::<K>();
    let value_type_name = std::any::type_name::<QV>();
    let key_size = std::mem::size_of::<K>();
    let value_size = std::mem::size_of::<QV>();

    // Decide how to store the entries: either inline as a Map, or as a
    // compressed payload written into `file` (if provided), or as a stable
    // 128-bit hash when no file is provided.
    let entries_value = inspect::Value::Map(entries_map);

    // Always compute a stable hash for the entries; store it under the
    // `value` field. If a file handle is provided, also serialize/compress
    // and stream the entries to the file, returning the offset in the
    // `entries` field. If no file is provided, keep the `entries` inline
    // as a Map so consumers can inspect it directly.
    use std::hash::Hash;
    use rustc_hashes::Hash128;
    use rustc_data_structures::stable_hasher::StableHasher;

    let mut hasher = StableHasher::new();
    entries_value.hash(&mut hasher);
    let h = hasher.finish::<Hash128>();
    let value_field = inspect::Value::UInt(h.as_u128());

    let stored_entries = if let Some(file) = state.file.as_deref_mut() {
        // Serialize
        let ser = match bincode::serialize(&entries_value) {
            Ok(b) => b,
            Err(_) => return (name, inspect::Value::String("<serialize-failed>".into())),
        };


        // Stream-compress directly into the provided file using Snappy's
        // FrameEncoder. Capture the file offset before writing so we can
        // compute the compressed length as the difference in file position
        // after writing.
        let offset = match file.seek(SeekFrom::Current(0)) {
            Ok(o) => o,
            Err(_) => return (name, inspect::Value::String("<seek-failed>".into())),
        };

        let mut encoder = FrameEncoder::new(file);
        if encoder.write_all(&ser).is_err() {
            return (name, inspect::Value::String("<compress-failed>".into()));
        }
        if encoder.flush().is_err() {
            return (name, inspect::Value::String("<compress-failed>".into()));
        }

        // Query the underlying file position to compute compressed length.
        let new_pos = match encoder.get_mut().seek(SeekFrom::Current(0)) {
            Ok(p) => p,
            Err(_) => return (name, inspect::Value::String("<seek-failed>".into())),
        };
        let compressed_len = (new_pos - offset) as u128;

        // Drop the encoder to release the mutable borrow on the file. We
        // explicitly discard the returned file handle since it's not needed
        // here.
        let _ = encoder.into_inner();

        // Store both offset and length of the compressed payload.
        let mut m: ::std::collections::BTreeMap<inspect::Value, inspect::Value> =
            ::std::collections::BTreeMap::new();
        m.insert(
            inspect::Value::String("offset".into()),
            inspect::Value::UInt(offset as u128),
        );
        m.insert(inspect::Value::String("len".into()), inspect::Value::UInt(compressed_len));

        inspect::Value::Map(m)
    } else {
        // No file: keep the entries inline so callers can inspect them.
        entries_value
    };

    let mut out_map: Vec<(inspect::Value, inspect::Value)> = Vec::new();
    // Only include the `entries` field when we actually wrote a payload to a
    // file; if no file was provided we skip the `entries` field and only
    // provide the stable `value` hash so callers can still verify contents.
    if state.file.is_some() {
        out_map.push((inspect::Value::String("entries".into()), stored_entries));
    }
    out_map.push((inspect::Value::String("value".into()), value_field));
    out_map.push((inspect::Value::String("key_type".into()), inspect::Value::String(key_type_name.into())));
    out_map.push((inspect::Value::String("value_type".into()), inspect::Value::String(value_type_name.into())));
    out_map.push((inspect::Value::String("key_size".into()), inspect::Value::UInt(key_size as u128)));
    out_map.push((inspect::Value::String("value_size".into()), inspect::Value::UInt(value_size as u128)));

    // Convert out_map Vec to BTreeMap before returning
    let mut ret_map: ::std::collections::BTreeMap<inspect::Value, inspect::Value> =
        ::std::collections::BTreeMap::new();
    for (k, v) in out_map.into_iter() {
        ret_map.insert(k, v);
    }
    (name, inspect::Value::Map(ret_map))
}
