use std::marker::PhantomData;

use rustc_data_structures::inspect::{self, EnumVariantSchema, Schema, SchemaRef, Value, Write};
use rustc_data_structures::stable_hasher::{HashStable, SpanArgs, StructureState};
use rustc_hir::def_id::CrateNum;
use rustc_middle::ty::TyCtxt;
use rustc_query_system::ich::StableHashingContext;    use std::hash::Hash;
use rustc_hashes::Hash128;
use rustc_data_structures::stable_hasher::StableHasher;

use rustc_span::{CachingSourceMapView, Pos, Span};

// NOTE: `PER_QUERY_COLLECT_STRUCTURES_FNS` is generated by the query
// macro into the plumbing module; do not import it here.
use crate::PER_QUERY_COLLECT_STRUCTURES_FNS;
use std::fs;
use std::collections::BTreeMap;
use std::io::{Seek, SeekFrom};
use std::path::PathBuf;
use rustc_span::def_id::LOCAL_CRATE;
use snap::write::FrameEncoder;
use std::io::Write as IoWrite;
// Cursor was used in an earlier approach; no longer needed.

fn def_path_value<'tcx>(
    tcx: TyCtxt<'tcx>,
    crate_num: u32,
    index: u32,
    state: &mut rustc_data_structures::inspect::StructureState<'_, StableHashingContext<'_>>,
    w: &mut dyn rustc_data_structures::inspect::Write,
) {
    // Construct a `DefId` from the supplied `u32` crate/def indices
    // and return an `inspect::Value::String` containing the def path.
    let def_id = rustc_span::def_id::DefId {
        krate: rustc_span::def_id::CrateNum::from_u32(crate_num),
        index: rustc_span::def_id::DefIndex::from_u32(index),
    };
    // New API: directly call the def_path callback on the provided state/writer.
    (state.def_path)(crate_num, index, state, w);
}

fn crate_num_value<'tcx>(
    tcx: TyCtxt<'tcx>,
    crate_num: u32,
    state: &mut rustc_data_structures::inspect::StructureState<'_, StableHashingContext<'_>>,
    w: &mut dyn rustc_data_structures::inspect::Write,
) {
    let stable = tcx.def_path_hash(CrateNum::from_u32(crate_num).as_def_id()).stable_crate_id();
    w.write_uint(stable.as_u64() as u128);
}

fn span_value<'tcx>(
    tcx: TyCtxt<'tcx>,
    span_args: SpanArgs,
    state: &mut rustc_data_structures::inspect::StructureState<'_, StableHashingContext<'_>>,
    w: &mut dyn rustc_data_structures::inspect::Write,
) {
    let span = Span::from_args(span_args);

    let span = span.data_untracked();
    if span.is_dummy() {
        static SCHEMA: SchemaRef = SchemaRef::new(Schema::Enum {
            path: "Span",
            variant_name: "Dummy",
            variant: EnumVariantSchema::Unit,
        });
        state.write_schema_header(&SCHEMA, w);
        return;
    }

    let parent = span.parent.map(|parent| tcx.def_span(parent).data_untracked());
    if let Some(parent) = parent
        && parent.contains(span)
    {
        // This span is enclosed in a definition: only hash the relative position. This catches
        // a subset of the cases from the `file.contains(parent.lo)`. But we can do this check
        // cheaply without the expensive `span_data_to_lines_and_cols` query.
        let lo = (span.lo - parent.lo).to_u32();
        let hi = (span.hi - parent.lo).to_u32();
        static SCHEMA: SchemaRef = SchemaRef::new(Schema::Enum {
            path: "Span",
            variant_name: "Relative",
            variant: EnumVariantSchema::Named(&["ctxt", "parent", "lo", "hi"]),
        });
        state.write_schema_header(&SCHEMA, w);
        w.write_bool(span.ctxt.is_root());
        w.write_uint(span.parent.map(|p| p.local_def_index.as_u32() as u128).unwrap_or(0));
        w.write_uint(lo as u128);
        w.write_uint(hi as u128);
        return;
    }

    let mut caching = CachingSourceMapView::new(tcx.sess.source_map());

    // If this is not an empty or invalid span, we want to hash the last position that belongs
    // to it, as opposed to hashing the first position past it.
    let Some((file, line_lo, col_lo, line_hi, col_hi)) = caching.span_data_to_lines_and_cols(&span)
    else {
        static SCHEMA: SchemaRef = SchemaRef::new(Schema::Enum { path: "Span", variant_name: "Dummy", variant: EnumVariantSchema::Unit });
        state.write_schema_header(&SCHEMA, w);
        return;
    };

    if let Some(parent) = parent
        && file.contains(parent.lo)
    {
        // This span is relative to another span in the same file,
        // only hash the relative position.
        let lo = span.lo.0.wrapping_sub(parent.lo.0);
        let hi = span.hi.0.wrapping_sub(parent.lo.0);
        static SCHEMA: SchemaRef = SchemaRef::new(Schema::Enum {
            path: "Span",
            variant_name: "Relative",
            variant: EnumVariantSchema::Named(&["ctxt", "parent", "lo", "hi"]),
        });
        state.write_schema_header(&SCHEMA, w);
        w.write_bool(span.ctxt.is_root());
        w.write_uint(span.parent.map(|p| p.local_def_index.as_u32() as u128).unwrap_or(0));
        w.write_uint(lo as u128);
        w.write_uint(hi as u128);
        return;
    }

    // Hash both the length and the end location (line/column) of a span. If we hash only the
    // length, for example, then two otherwise equal spans with different end locations will
    // have the same hash. This can cause a problem during incremental compilation wherein a
    // previous result for a query that depends on the end location of a span will be
    // incorrectly reused when the end location of the span it depends on has changed (see
    // issue #74890). A similar analysis applies if some query depends specifically on the
    // length of the span, but we only hash the end location. So hash both.
    let len = (span.hi - span.lo).0;

    static SCHEMA: SchemaRef = SchemaRef::new(Schema::Enum {
        path: "Span",
        variant_name: "Valid",
        variant: EnumVariantSchema::Named(&[
            "ctxt",
            "parent",
            "stable_id",
            "col_lo",
            "col_hi",
            "line_lo",
            "line_hi",
            "len",
        ]),
    });
        state.write_schema_header(&SCHEMA, w);
    w.write_bool(span.ctxt.is_root());
    w.write_uint(span.parent.map(|p| p.local_def_index.as_u32() as u128).unwrap_or(0));
    // `StableSourceFileId` is a newtype around `Hash128` with a private field.
    // For export, write a deterministic string form.
    w.write_string(&format!("{:?}", file.stable_id));
    w.write_uint(col_lo.0 as u128);
    w.write_uint(col_hi.0 as u128);
    w.write_uint(line_lo as u128);
    w.write_uint(line_hi as u128);
    w.write_uint(len as u128);
}

/// Collects structural representations for all queries and returns
/// them as an inspect::Value map: query_name -> { key -> value }
pub(crate) fn collect_all_query_structures<'tcx>(
    tcx: TyCtxt<'tcx>,
    // Optional file to which per-query compressed payloads will be written as
    // we iterate over PER_QUERY_COLLECT_STRUCTURES_FNS. We need Seek to
    // obtain current offsets. If `None` is passed, we will not write payloads
    // but instead hash each per-query `Map` value and store that hash.
    mut file: Option<&mut fs::File>,
    state: &mut StructureState<'_, StableHashingContext<'_>>,
) -> Result<inspect::Value, std::io::Error> {
    // hashing/compression is handled per-query in `assemble_query_structures`

    let mut entries_map: BTreeMap<inspect::Value, inspect::Value> = BTreeMap::new();

    for f in PER_QUERY_COLLECT_STRUCTURES_FNS.iter() {
        let (name, value) = f(tcx, state, &mut file)?;
        entries_map.insert(inspect::Value::String(name.into()), value);
    }

    Ok(inspect::Value::Map(entries_map))
}

// Module-scoped helper for exporting query structures when the feature is enabled.
pub(crate) fn export_queries_if_enabled<'tcx>(tcx: TyCtxt<'tcx>) {
    // Check option enablement on the unstable options struct.
    if !tcx.sess.opts.unstable_opts.export_queries {
        return;
    }

    let dir = match &tcx.sess.opts.unstable_opts.export_queries_dir {
        Some(d) => d.clone(),
        None => return,
    };

    let _prof_timer = tcx.sess.prof.verbose_generic_activity("export_queries");

    // Determine crate name and stable crate id early so the directory
    // scanning can use them. Use the stable crate id (not the crate
    // hash) in the filename to make the exported filename stable across
    // builds where only the crate hash may differ.
    let crate_name = tcx.crate_name(LOCAL_CRATE).to_string();
    let crate_stable_id = tcx.stable_crate_id(LOCAL_CRATE).as_u64();
    let crate_id_str = format!("{:08x}", crate_stable_id);

    // Ensure directory exists; if creation fails, emit a warning diagnostic.
    if let Err(e) = fs::create_dir_all(&dir) {
        tcx.sess.dcx().emit_warn(crate::error::ExportQueriesCreateDirFail {
            path: dir.as_path(),
            err: e.to_string(),
        });
        return;
    }

    // Compute a stable hash of the top-level structures (no file) and use
    // that as the unique filename. If the file already exists, return
    // without error.
    // Construct a StructureState once and pass it down to collection functions.
    let mut state: StructureState<'_, StableHashingContext<'_>> = StructureState {
        schema_list: Default::default(),
        span_value: &|args, st, w| span_value(tcx, args, st, w),
        def_path: &|crate_num, index, st, w| def_path_value(tcx, crate_num, index, st, w),
        crate_num: &|crate_num, st, w| crate_num_value(tcx, crate_num, st, w),
        _marker: std::marker::PhantomData,
    };

    let top_no_file = {
        let _prof_timer = tcx.sess.prof.verbose_generic_activity("export_queries_hash_pass");

        match collect_all_query_structures(tcx, None, &mut state) {
            Ok(v) => v,
            Err(_) => return,
        }
    };

    use std::hash::Hash;
    use rustc_hashes::Hash128;
    use rustc_data_structures::stable_hasher::StableHasher;

    let mut hasher = StableHasher::new();
    top_no_file.hash(&mut hasher);
    let h = hasher.finish::<Hash128>();
    let hex = format!("{:032x}", h.as_u128());

    let filename = format!("{}.{}.content-{}.rcqe", crate_name, crate_id_str, hex);
    let mut path = PathBuf::from(&dir);
    path.push(&filename);

    if path.exists() {
        // File with identical exported content already exists; nothing to do.
        return;
    }

    // Create the file to stream payloads into.
    let mut f = match fs::File::create(&path) {
        Ok(file) => file,
        Err(e) => {
            tcx.sess.dcx().emit_warn(crate::error::ExportQueriesFileWriteFail {
                path: path.as_path(),
                err: e.to_string(),
            });
            return;
        }
    };

    // Write a fixed, constant 8-byte u64 header so tools can recognize
    // this file format. The value is chosen to look random but remains
    // constant across runs.
    const MAGIC_HEADER_U64: u64 = 0x9e3793b97f4a7c15u64;
    let header_bytes = MAGIC_HEADER_U64.to_le_bytes();
    if f.write_all(&header_bytes).is_err() {
        tcx.sess.dcx().emit_warn(crate::error::ExportQueriesFileWriteFail {
            path: path.as_path(),
            err: "failed to write header".to_string(),
        });
        return;
    }

    // Collect and stream per-query payloads into `f`. This will write the
    // compressed per-query payloads and return a top-level `Value` where
    // those entries have been replaced with their offsets.
    let value = match collect_all_query_structures(tcx, Some(&mut f), &mut state) {
        Ok(v) => v,
        Err(_) => return,
    };

    // Now write the serialized top-level Value and footer length.
    let bytes = match bincode::serialize(&value) {
        Ok(b) => b,
        Err(_) => return,
    };

    if f.write_all(&bytes).is_err() {
        tcx.sess.dcx().emit_warn(crate::error::ExportQueriesFileWriteFail {
            path: path.as_path(),
            err: "failed to write top-level value".to_string(),
        });
        return;
    }
    // Store only the length of the serialized top-level value (u64 LE).
    // Readers can use this length to locate and validate the footer.
    let footer_len = bytes.len() as u64;
    if f.write_all(&footer_len.to_le_bytes()).is_err() {
        tcx.sess.dcx().emit_warn(crate::error::ExportQueriesFileWriteFail {
            path: path.as_path(),
            err: "failed to write footer length".to_string(),
        });
        return;
    }

    // Write a trailer magic so readers can quickly sanity-check that the
    // file ended as expected, then flush the OS buffers. Emit a warning
    // if either write or flush fails.
    let trailer_bytes = MAGIC_HEADER_U64.to_le_bytes();
    if f.write_all(&trailer_bytes).is_err() {
        tcx.sess.dcx().emit_warn(crate::error::ExportQueriesFileWriteFail {
            path: path.as_path(),
            err: "failed to write trailer magic".to_string(),
        });
        return;
    }

    // Ensure all writes succeeded by flushing the OS buffers. If flush
    // fails, emit a diagnostic so callers know the export may be incomplete.
    if f.flush().is_err() {
        tcx.sess.dcx().emit_warn(crate::error::ExportQueriesFileWriteFail {
            path: path.as_path(),
            err: "failed to flush output file".to_string(),
        });
        return;
    }

    // The remainder of the function finishes above (file creation, streaming,
    // writing top-level value and footer). No further actions needed here.
}

/// Assemble the final per-query structure map from the entries and metadata.
pub(crate) fn assemble_query_structures<'tcx, K, QV, C>(
    _tcx: TyCtxt<'tcx>,
    name: String,
    cache: &C,
    state: &mut StructureState<'_, StableHashingContext<'_>>,
    file: &mut Option<&mut std::fs::File>,
    mut write_value: impl FnMut(&C::Value, &mut StructureState<'_, StableHashingContext<'_>>, &mut inspect::IoWriter<FrameEncoder<&mut std::fs::File>>),
    mut hash_value: impl FnMut(&C::Value, &mut StructureState<'_, StableHashingContext<'_>>, &mut inspect::Hasher),
) -> Result<(String, inspect::Value), std::io::Error>
where
    C: rustc_query_system::query::QueryCache<Key = K>,
    K: Clone,
    for<'s> K: HashStable<StableHashingContext<'s>>,
    QV: Sized,
    C::Value: Copy,
{
    let mut cached: Vec<(K, C::Value)> = Vec::new();
    cache.iter(&mut |k, v, _| {
        cached.push((k.clone(), *v));
    });

    let mut hashed: Vec<_> = cached.iter().map(|(k, v)| {
        let mut hasher = inspect::Hasher::new();
        k.structure(state, &mut hasher);
        let key_hash = hasher.finish();

        let mut hasher = inspect::Hasher::new();
        hash_value(v, state, &mut hasher);
        let value_hash = hasher.finish();
        (key_hash, value_hash, k, v)
        }).collect();
    hashed.sort_by_key(|v| v.0);

    let stored_entries = if let Some(file_slot) = file.as_mut() {
        let f: &mut std::fs::File = &mut **file_slot;
        let offset = f.seek(SeekFrom::Current(0))?;

        let mut encoder = FrameEncoder::new(f);
        let mut writer = inspect::IoWriter::wrap(encoder);

        writer.write_map_header(hashed.len());

        for (_, _, k, v) in hashed.iter() {
            k.structure(state, &mut writer);
            write_value(v, state, &mut writer);
        }

        let (mut encoder, maybe_err) = writer.into_inner();
        // Propagate any cached write error from IoWriter before flushing.
        if let Some(e) = maybe_err {
            return Err(e);
        }
        encoder.flush()?;
        // `FrameEncoder::into_inner` returns a Result with the inner writer
        // or an IntoInnerError. Map any error into an `std::io::Error`.
        match encoder.into_inner() {
            Ok(_inner_file) => {}
            Err(e) => {
                return Err(std::io::Error::new(std::io::ErrorKind::Other, format!("snap into_inner error: {:?}", e)));
            }
        }

        // `f` has been moved/used, but `encoder.into_inner()` returns `&mut fs::File`.
        // Re-acquire the position from the file slot.
        let new_pos = file_slot.seek(SeekFrom::Current(0))?;
        let compressed_len = new_pos - offset;

        Some((offset, compressed_len))
    } else {
        None
    };

    let key_type_name = std::any::type_name::<K>();
    let value_type_name = std::any::type_name::<QV>();
    let key_size = std::mem::size_of::<K>();
    let value_size = std::mem::size_of::<QV>();

    // Decide how to store the entries: either inline as a Map, or as a
    // compressed payload written into `file` (if provided), or as a stable
    // 128-bit hash when no file is provided.

    let mut hasher = StableHasher::new();

    for (key_hash, value_hash, _, _) in hashed.iter() {
        key_hash.hash(&mut hasher);
        value_hash.hash(&mut hasher);
    }
    let h = hasher.finish::<Hash128>();
    let hash_field = inspect::Value::UInt(h.as_u128());

    let mut out_map: BTreeMap<inspect::Value, inspect::Value> = BTreeMap::new();
    // Only include the `entries` field when we actually wrote a payload to a
    // file; if no file was provided we skip the `entries` field and only
    // provide the stable `value` hash so callers can still verify contents.
    if let Some((offset, compressed_len)) = stored_entries {
        // Store both offset and length of the compressed payload.
        let mut m: BTreeMap<inspect::Value, inspect::Value> = BTreeMap::new();
        m.insert(
            inspect::Value::String("offset".into()),
            inspect::Value::UInt(offset as u128),
        );
        m.insert(inspect::Value::String("len".into()), inspect::Value::UInt(compressed_len as u128));

        out_map.insert(inspect::Value::String("entries".into()), inspect::Value::Map(m));
    }
    out_map.insert(inspect::Value::String("hash".into()), hash_field);
    out_map.insert(
        inspect::Value::String("key_type".into()),
        inspect::Value::String(key_type_name.into()),
    );
    out_map.insert(
        inspect::Value::String("value_type".into()),
        inspect::Value::String(value_type_name.into()),
    );
    out_map.insert(
        inspect::Value::String("key_size".into()),
        inspect::Value::UInt(key_size as u128),
    );
    out_map.insert(
        inspect::Value::String("value_size".into()),
        inspect::Value::UInt(value_size as u128),
    );

    Ok((name, inspect::Value::Map(out_map)))
}
