[package]
authors = ["The Rust Project Developers"]
name = "rustc_typeck"
version = "0.0.0"

[lib]
name = "rustc_typeck"
path = "lib.rs"
crate-type = ["dylib"]
test = false

[dependencies]
arena = { path = "../libarena" }
log = "0.4"
rustc = { path = "../librustc" }
rustc_data_structures = { path = "../librustc_data_structures" }
rustc_errors = { path = "../librustc_errors" }
rustc_platform_intrinsics = { path = "../librustc_platform_intrinsics" }
rustc_target = { path = "../librustc_target" }

syntax = { path = "../libsyntax" }
syntax_pos = { path = "../libsyntax_pos" }

[dependencies.smallvec]
git = "https://github.com/Zoxc/rust-smallvec"
branch = "push_light_def"
features = ["union", "likely", "push_light"]
