pr: none
trigger:
- try

variables:
- group: prod-credentials

jobs:
- job: Linux
  timeoutInMinutes: 600
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: steps/run.yml
  strategy:
    matrix:
      dist-various-2: {}
      armhf-gnu: {}
      arm-android: {}
      dist-s390x-linux: {}
      wasm32: {}
