[package]
authors = ["The Rust Project Developers"]
name = "arena"
version = "0.0.0"

[lib]
name = "arena"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
rustc-rayon-core = "0.1.1"
rustc_data_structures = { path = "../librustc_data_structures" }